version: '3'

services:
  uaa:
    image: pcfseceng/uaa
    volumes: ["./config/uaa.yml:/uaa/uaa.yml"]
    ports: [8090:8080]
    restart: always
    networks:
      shared:
        aliases: 
          - uaa

  credhub:
    image: pcfseceng/credhub
    volumes: 
      - "./utils/credhub-install.sh:/app/credhub-install.sh:ro"
    ports: ["9000:9000"]
    links: ["uaa:uaa"]
    depends_on: [uaa]
    environment:
      UAA_URL: http://uaa:8080/uaa
      UAA_INTERNAL_URL: http://uaa:8080/uaa
    networks:
      shared:
        aliases: 
          - credhub
  
  db:
    image: postgres
    depends_on: [credhub]
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    networks:
      shared:
        aliases: 
          - db

  web:
    image: concourse/concourse
    volumes: 
      - "./keys/server_ca_cert.pem:/tmp/credhub.cacert"
      - "./keys/web:/concourse-keys"
    command: web
    links: ["credhub:credhub"]
    depends_on: [credhub,db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CREDHUB_URL: https://credhub:9000/api/
      CONCOURSE_CREDHUB_CLIENT_ID: credhub_client
      CONCOURSE_CREDHUB_CLIENT_SECRET: secret
      CONCOURSE_CREDHUB_CA_CERT: /tmp/credhub.cacert
      CONCOURSE_CREDHUB_INSECURE_SKIP_VERIFY: "true"
    networks:
      shared:
        aliases: 
          - web

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
    networks:
      shared:
        aliases: 
          - worker

networks:
  shared:
